import { useState } from 'react';

import {
  ApiError,
  createOrGetAIInsight,
  type AIInsightOut,
  type AIInsightTarget,
} from '../../api/client';
import { friendlyErrorLines } from '../../api/errors';

type InsightState =
  | { kind: 'idle' }
  | { kind: 'loading' }
  | { kind: 'loaded'; insight: AIInsightOut }
  | { kind: 'error'; error: ApiError };

export interface AIInsightPanelProps {
  target: AIInsightTarget;
}

// A calculation or comparison already has its own real numbers -
// generated_text is never fed back in as a number source anywhere. This
// panel only ever renders it as prose in a visually distinct block (see
// .ai-insight-panel in index.css), never as a value in a table, dl, or
// anywhere formatCurrency() is used - that boundary is enforced by
// construction (this component simply has no such rendering path), not
// by a rule someone has to remember to follow.
export function AIInsightPanel({ target }: AIInsightPanelProps) {
  const [state, setState] = useState<InsightState>({ kind: 'idle' });

  function generate() {
    setState({ kind: 'loading' });
    createOrGetAIInsight(target)
      .then((insight) => setState({ kind: 'loaded', insight }))
      .catch((error: unknown) => {
        const apiError =
          error instanceof ApiError
            ? error
            : new ApiError('unknown_error', 'An unexpected error occurred', null);
        setState({ kind: 'error', error: apiError });
      });
  }

  return (
    <div className="ai-insight-panel">
      <h3>AI-generated insight</h3>

      {state.kind === 'idle' && (
        <>
          <p>
            Get a plain-language explanation or negotiation framing based on the figures above,
            generated by AI.
          </p>
          <button type="button" onClick={generate}>
            Generate AI insight
          </button>
        </>
      )}

      {state.kind === 'loading' && <p>Generating insight…</p>}

      {state.kind === 'error' && (
        <>
          <div role="alert" className="error-banner">
            <ul>
              {friendlyErrorLines(state.error).map((line) => (
                <li key={line}>{line}</li>
              ))}
            </ul>
          </div>
          <button type="button" onClick={generate}>
            Try again
          </button>
        </>
      )}

      {state.kind === 'loaded' && (
        <div className="ai-insight-result">
          <p className="ai-insight-label">AI-generated interpretation</p>
          <p>{state.insight.generated_text}</p>
          <p className="ai-insight-disclaimer">
            Generated by AI from the figures above - it does not compute, verify, or add any numbers
            of its own. Every number it states is checked against the calculation above before being
            shown to you.
          </p>
        </div>
      )}
    </div>
  );
}
