/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness + readiness check.
     *
     *     "api" reflects the process being up (always "ok" if this code runs at
     *     all). "database" reflects the SELECT 1 readiness check. Overall status
     *     is "degraded" with a 503 if any check fails, so a load balancer or
     *     orchestrator polling this endpoint can distinguish ready from not-ready
     *     by status code alone, not just by parsing the body.
     */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations['register_api_v1_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Countries */
    get: operations['list_countries_api_v1_countries_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/countries/{country_code}/tax-rule-sets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Tax Rule Sets */
    get: operations['list_tax_rule_sets_api_v1_countries__country_code__tax_rule_sets_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calculations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Calculation */
    post: operations['create_calculation_api_v1_calculations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/calculations/mine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List My Calculations
     * @description Auth is required here (unlike POST /calculations) - there is no
     *     such thing as anonymous history to return, so "not logged in" really
     *     is a blocking condition for this one endpoint.
     */
    get: operations['list_my_calculations_api_v1_calculations_mine_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccessTokenOut */
    AccessTokenOut: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** CalculationOut */
    CalculationOut: {
      /** Id */
      id: number;
      /** Compensation Input Id */
      compensation_input_id: number;
      /** User Id */
      user_id: number | null;
      /** Engine Version */
      engine_version: string;
      /** Gross Amount */
      gross_amount: string;
      /** Total Compensation Amount */
      total_compensation_amount: string;
      /** Tax Rule Set Id */
      tax_rule_set_id: number | null;
      /** Total Tax Amount */
      total_tax_amount: string | null;
      /** Net Amount */
      net_amount: string | null;
      /** Breakdown */
      breakdown: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** CompensationComponentIn */
    CompensationComponentIn: {
      component_type: components['schemas']['ComponentType'];
      /** Amount */
      amount: number | string;
      /** Currency Code */
      currency_code: string;
      /** Description */
      description?: string | null;
    };
    /** CompensationInputCreate */
    CompensationInputCreate: {
      /** Country Code */
      country_code: string;
      /** Job Family Id */
      job_family_id?: number | null;
      /** Experience Level Id */
      experience_level_id?: number | null;
      /** Employment Type Id */
      employment_type_id?: number | null;
      /** Regime */
      regime?: string | null;
      /** Filing Status */
      filing_status?: string | null;
      /** Target Currency Code */
      target_currency_code: string;
      /** As Of Date */
      as_of_date?: string | null;
      /** Components */
      components: components['schemas']['CompensationComponentIn'][];
    };
    /**
     * ComponentType
     * @description A typed compensation line item. Composable rather than fixed columns
     *     (base_salary, bonus, ...) — what counts as compensation varies by
     *     country and employment type (13th-month pay, RSUs, housing allowances),
     *     and retrofitting fixed columns later would be a real rewrite.
     * @enum {string}
     */
    ComponentType: 'base' | 'bonus' | 'equity' | 'benefit' | 'allowance';
    /** CountryOut */
    CountryOut: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      default_currency: components['schemas']['CurrencyOut'];
    };
    /** CurrencyOut */
    CurrencyOut: {
      /** Code */
      code: string;
      /** Name */
      name: string;
      /** Symbol */
      symbol: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthCheckResponse */
    HealthCheckResponse: {
      /** Status */
      status: string;
      /** Checks */
      checks: {
        [key: string]: string;
      };
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** PaginatedCalculationsOut */
    PaginatedCalculationsOut: {
      /** Items */
      items: components['schemas']['CalculationOut'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** TaxBracketOut */
    TaxBracketOut: {
      component: components['schemas']['TaxComponent'];
      /** Lower Bound */
      lower_bound: string;
      /** Upper Bound */
      upper_bound: string | null;
      /** Rate */
      rate: string;
    };
    /**
     * TaxComponent
     * @description What a TaxBracket row represents. Deliberately generic — new
     *     components (a future country's own named levy) extend this enum rather
     *     than requiring new tables or country-specific code paths.
     * @enum {string}
     */
    TaxComponent: 'income_tax' | 'social_security' | 'medicare' | 'medicare_additional_surtax';
    /** TaxRuleSetOut */
    TaxRuleSetOut: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Regime */
      regime: string | null;
      /** Filing Status */
      filing_status: string | null;
      /** Standard Deduction */
      standard_deduction: string | null;
      /**
       * Effective Date
       * Format: date
       */
      effective_date: string;
      /** End Date */
      end_date: string | null;
      /** Source Url */
      source_url: string | null;
      currency: components['schemas']['CurrencyOut'];
      /** Tax Brackets */
      tax_brackets: components['schemas']['TaxBracketOut'][];
    };
    /** TokenPairOut */
    TokenPairOut: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserOut */
    UserOut: {
      /** Id */
      id: number;
      /** Email */
      email: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthCheckResponse'];
        };
      };
    };
  };
  register_api_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenPairOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessTokenOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LogoutRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_countries_api_v1_countries_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CountryOut'][];
        };
      };
    };
  };
  list_tax_rule_sets_api_v1_countries__country_code__tax_rule_sets_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        country_code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TaxRuleSetOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_calculation_api_v1_calculations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CompensationInputCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CalculationOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_my_calculations_api_v1_calculations_mine_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedCalculationsOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
