"""add market data points and job family occupation mappings

Revision ID: 285eaec49228
Revises: a38684d2734c
Create Date: 2026-08-17 06:09:39.070201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '285eaec49228'
down_revision: Union[str, Sequence[str], None] = 'a38684d2734c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_family_occupation_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_family_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.String(length=32), nullable=False, comment="Occupational classification standard, e.g. 'SOC-2018'."),
    sa.Column('external_code', sa.String(length=16), nullable=False, comment="Code within `taxonomy`, e.g. '151252' for SOC 15-1252."),
    sa.Column('external_label', sa.String(length=256), nullable=False, comment="The source's own name for this occupation, stored verbatim so the UI can show exactly how broad the bucket is rather than paraphrasing it."),
    sa.Column('match_quality', sa.Enum('CLOSE', 'BROAD', 'POOR', name='match_quality'), nullable=False),
    sa.Column('match_note', sa.Text(), nullable=False, comment='Plain-language statement of what this mapping does and does not capture. Required, not nullable: every mapping is lossy in some way and saying how is the point.'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_family_id', 'country_id', 'taxonomy', 'external_code', name='uq_job_family_occupation_mappings_family_country_taxonomy_code')
    )
    op.create_index('ix_job_family_occupation_mappings_lookup', 'job_family_occupation_mappings', ['country_id', 'taxonomy', 'external_code'], unique=False)
    op.create_table('market_data_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('taxonomy', sa.String(length=32), nullable=False),
    sa.Column('external_code', sa.String(length=16), nullable=False),
    sa.Column('external_label', sa.String(length=256), nullable=False),
    sa.Column('geographic_scope', sa.Enum('NATIONAL', 'STATE', 'METRO', name='geographic_scope'), nullable=False),
    sa.Column('area_code', sa.String(length=16), nullable=False, comment="Source's own area code, e.g. OEWS '0000000' for National."),
    sa.Column('area_name', sa.String(length=128), nullable=False),
    sa.Column('percentile_10', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentile_25', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentile_50', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentile_75', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('percentile_90', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('mean_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employment_count', sa.Integer(), nullable=True, comment='Estimated number of workers in this occupation/area - a rough proxy for how much weight the estimate can bear.'),
    sa.Column('reference_period', sa.Date(), nullable=False, comment="First day of the period the estimate DESCRIBES (e.g. 2025-05-01 for OEWS 'May 2025'), which is not when it was published - see published_date."),
    sa.Column('reference_period_label', sa.String(length=64), nullable=False, comment="The source's own name for the period, e.g. 'May 2025'."),
    sa.Column('published_date', sa.Date(), nullable=True, comment='When the source released this estimate. Stored separately from reference_period because the lag is large and material: OEWS May 2025 data was released 2026-05-15.'),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('methodology_note', sa.Text(), nullable=False, comment="Sample/collection method and known limitations, in the source's own terms."),
    sa.Column('excludes_variable_compensation', sa.Boolean(), nullable=False),
    sa.Column('wage_definition_note', sa.Text(), nullable=False, comment="Precisely what this figure counts as pay, in the source's own terms."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('percentile_10 IS NOT NULL OR percentile_25 IS NOT NULL OR percentile_50 IS NOT NULL OR percentile_75 IS NOT NULL OR percentile_90 IS NOT NULL OR mean_value IS NOT NULL', name='ck_market_data_points_has_at_least_one_value'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'taxonomy', 'external_code', 'geographic_scope', 'area_code', 'reference_period', name='uq_market_data_points_natural_key')
    )
    op.create_index('ix_market_data_points_lookup', 'market_data_points', ['country_id', 'taxonomy', 'external_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_data_points_lookup', table_name='market_data_points')
    op.drop_table('market_data_points')
    op.drop_index('ix_job_family_occupation_mappings_lookup', table_name='job_family_occupation_mappings')
    op.drop_table('job_family_occupation_mappings')
    # ### end Alembic commands ###

    # Hand-added, NOT autogenerated - and not a hypothetical tidy-up.
    # create_table() creates a PostgreSQL ENUM type implicitly for each
    # sa.Enum column, but autogenerate's downgrade only drops the TABLES,
    # silently leaving the types behind. Verified by running the real
    # upgrade -> downgrade -> upgrade cycle against the dev database
    # before writing this: the second upgrade failed with
    # `psycopg.errors.DuplicateObject: type "match_quality" already
    # exists`. Without these two lines the migration is not genuinely
    # reversible, which would only ever be discovered during an actual
    # rollback - the worst possible moment.
    sa.Enum(name='geographic_scope').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='match_quality').drop(op.get_bind(), checkfirst=False)
