"""add tax bracket integrity constraints and column comments

Revision ID: 3d20c3436ea1
Revises: 0e018637e242
Create Date: 2026-08-15 07:18:04.475935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d20c3436ea1'
down_revision: Union[str, Sequence[str], None] = '0e018637e242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax_brackets', 'lower_bound',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment="Inclusive lower bound of this bracket, in the rule set's currency.",
               existing_nullable=False)
    op.alter_column('tax_brackets', 'upper_bound',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment="Exclusive upper bound, in the rule set's currency. NULL = unbounded top bracket.",
               existing_nullable=True)
    op.create_unique_constraint('uq_tax_brackets_rule_set_component_lower_bound', 'tax_brackets', ['tax_rule_set_id', 'component', 'lower_bound'])
    op.create_check_constraint('ck_tax_brackets_upper_gt_lower', 'tax_brackets', 'upper_bound IS NULL OR upper_bound > lower_bound')
    op.alter_column('tax_rule_sets', 'end_date',
               existing_type=sa.DATE(),
               comment='NULL means this rule set has no known end date (still current).',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tax_rule_sets', 'end_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='NULL means this rule set has no known end date (still current).',
               existing_nullable=True)
    op.drop_constraint('ck_tax_brackets_upper_gt_lower', 'tax_brackets', type_='check')
    op.drop_constraint('uq_tax_brackets_rule_set_component_lower_bound', 'tax_brackets', type_='unique')
    op.alter_column('tax_brackets', 'upper_bound',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment="Exclusive upper bound, in the rule set's currency. NULL = unbounded top bracket.",
               existing_nullable=True)
    op.alter_column('tax_brackets', 'lower_bound',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               comment=None,
               existing_comment="Inclusive lower bound of this bracket, in the rule set's currency.",
               existing_nullable=False)
    # ### end Alembic commands ###
