"""add compensation input, component, and calculation tables

Revision ID: 5d0e046a5357
Revises: 3d20c3436ea1
Create Date: 2026-08-15 09:57:53.503260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d0e046a5357'
down_revision: Union[str, Sequence[str], None] = '3d20c3436ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compensation_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('job_family_id', sa.Integer(), nullable=True),
    sa.Column('experience_level_id', sa.Integer(), nullable=True),
    sa.Column('employment_type_id', sa.Integer(), nullable=True),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('filing_status', sa.String(length=32), nullable=True),
    sa.Column('target_currency_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False, comment='Date used for tax rule set and exchange rate lookups.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], ),
    sa.ForeignKeyConstraint(['experience_level_id'], ['experience_levels.id'], ),
    sa.ForeignKeyConstraint(['job_family_id'], ['job_families.id'], ),
    sa.ForeignKeyConstraint(['target_currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compensation_input_id', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_compensation_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rule_set_id', sa.Integer(), nullable=True),
    sa.Column('total_tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gross_amount >= 0', name='ck_calculations_gross_non_negative'),
    sa.CheckConstraint('net_amount IS NULL OR net_amount >= 0', name='ck_calculations_net_non_negative'),
    sa.CheckConstraint('total_compensation_amount >= 0', name='ck_calculations_total_comp_non_negative'),
    sa.CheckConstraint('total_tax_amount IS NULL OR total_tax_amount >= 0', name='ck_calculations_total_tax_non_negative'),
    sa.ForeignKeyConstraint(['compensation_input_id'], ['compensation_inputs.id'], ),
    sa.ForeignKeyConstraint(['tax_rule_set_id'], ['tax_rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compensation_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compensation_input_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.Enum('BASE', 'BONUS', 'EQUITY', 'BENEFIT', 'ALLOWANCE', name='component_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.CheckConstraint('amount >= 0', name='ck_compensation_components_amount_non_negative'),
    sa.ForeignKeyConstraint(['compensation_input_id'], ['compensation_inputs.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compensation_components')
    # Same fix as migration 0e018637e242: autogenerate's drop_table doesn't
    # drop the Postgres enum type it implicitly created, which orphans it
    # and breaks the next upgrade with "type already exists".
    op.execute('DROP TYPE component_type')
    op.drop_table('calculations')
    op.drop_table('compensation_inputs')
    # ### end Alembic commands ###
