"""add ai_analysis_requests and ai_analysis_results tables

Revision ID: a38684d2734c
Revises: 5c7a965ea081
Create Date: 2026-08-16 14:52:32.176667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38684d2734c'
down_revision: Union[str, Sequence[str], None] = '5c7a965ea081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calculation_id', sa.Integer(), nullable=True),
    sa.Column('comparison_id', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(calculation_id IS NOT NULL AND comparison_id IS NULL) OR (calculation_id IS NULL AND comparison_id IS NOT NULL)', name='ck_ai_analysis_requests_exactly_one_target'),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analysis_requests_user_calculation', 'ai_analysis_requests', ['user_id', 'calculation_id'], unique=False)
    op.create_index('ix_ai_analysis_requests_user_comparison', 'ai_analysis_requests', ['user_id', 'comparison_id'], unique=False)
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('consistency_check_passed', sa.Boolean(), nullable=False),
    sa.Column('consistency_check_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['ai_analysis_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analysis_results')
    op.drop_index('ix_ai_analysis_requests_user_comparison', table_name='ai_analysis_requests')
    op.drop_index('ix_ai_analysis_requests_user_calculation', table_name='ai_analysis_requests')
    op.drop_table('ai_analysis_requests')
    # ### end Alembic commands ###
