"""add nullable user_id to calculations

Revision ID: ab4dbb6f8b88
Revises: 7ebceb58aba8
Create Date: 2026-08-15 17:31:18.569413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4dbb6f8b88'
down_revision: Union[str, Sequence[str], None] = '7ebceb58aba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('user_id', sa.Integer(), nullable=True))
    # Named explicitly (autogenerate emitted None here) - unlike the FK
    # constraints defined inline in a create_table() elsewhere in this
    # project, downgrade needs a real name to target with drop_constraint;
    # None can't be resolved to "the constraint Postgres auto-named at
    # create time" without a DB round-trip alembic doesn't do. Confirmed
    # by running the downgrade for real: it raised
    # sqlalchemy.exc.CompileError before this fix.
    op.create_foreign_key(
        'fk_calculations_user_id_users', 'calculations', 'users', ['user_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_calculations_user_id_users', 'calculations', type_='foreignkey')
    op.drop_column('calculations', 'user_id')
    # ### end Alembic commands ###
