"""add survey source fields to market data points

Revision ID: f3d360000ac9
Revises: 285eaec49228
Create Date: 2026-08-17 17:12:11.149171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d360000ac9'
down_revision: Union[str, Sequence[str], None] = '285eaec49228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_points', sa.Column('sample_size', sa.Integer(), nullable=True))
    op.add_column('market_data_points', sa.Column('experience_band_label', sa.String(length=32), nullable=True, comment="e.g. '6-10 yrs'. NULL = not broken down by experience."))
    op.add_column('market_data_points', sa.Column('experience_min_years', sa.Integer(), nullable=True))
    op.add_column('market_data_points', sa.Column('experience_max_years', sa.Integer(), nullable=True, comment="NULL with a non-NULL min means an open-ended top band (e.g. '11+ yrs')."))
    # Hand-corrected, NOT as autogenerated. Alembic emitted source_key as
    # nullable=False with no default, which fails outright against a table
    # that already holds rows - verified, not assumed: running the
    # generated version against the dev database (9 existing BLS rows)
    # produced `NotNullViolation: column "source_key" of relation
    # "market_data_points" contains null values`.
    #
    # The correct sequence is add-nullable, backfill, then enforce. The
    # backfill assigns 'bls_oews' because every pre-Phase-11 row came from
    # the single source that existed at the time - a fact about this
    # table's history, not a guess.
    op.add_column(
        'market_data_points',
        sa.Column('source_key', sa.String(length=32), nullable=True,
                  comment="Stable source id, e.g. 'bls_oews', 'stackoverflow_survey'."),
    )
    op.execute("UPDATE market_data_points SET source_key = 'bls_oews' WHERE source_key IS NULL")
    op.alter_column('market_data_points', 'source_key', nullable=False)
    op.add_column('market_data_points', sa.Column('representativeness_note', sa.Text(), nullable=True))

    # Also hand-added. Phase 10 sized external_code for short numeric SOC
    # codes; a survey's own identifier for a role is its descriptive
    # string ("Developer, embedded applications or devices", 43 chars),
    # which overflowed VARCHAR(16). Found by running the real seed:
    # `StringDataRightTruncation: value too long for type character
    # varying(16)`. Both columns widen together because they are joined
    # on this value.
    op.alter_column(
        'job_family_occupation_mappings', 'external_code',
        existing_type=sa.String(length=16), type_=sa.String(length=128),
        comment="Code within `taxonomy`, e.g. '151252' for SOC 15-1252, or a survey's own "
                "role label. Widened from 16 in Phase 11: a statistical classification uses "
                "short numeric codes, but a survey's identifier for a role IS its descriptive "
                "string (e.g. 'Developer, embedded applications or devices'). Storing the "
                "source's own value keeps the row traceable rather than inventing local slugs.",
        existing_comment="Code within `taxonomy`, e.g. '151252' for SOC 15-1252.",
    )
    op.alter_column('market_data_points', 'external_code',
                    existing_type=sa.String(length=16), type_=sa.String(length=128))

    # Also hand-added, and also found by running the real ingestion: the
    # Phase 10 CHECK requires every row to carry at least one figure, but
    # a SUPPRESSED survey cell has none by design - it exists so a
    # too-small sample is visible with its count rather than silently
    # absent. Relaxed narrowly: a row with no figures must still explain
    # itself with a sample_size, so a published-estimate source (which
    # has none) still cannot store an empty row.
    op.drop_constraint('ck_market_data_points_has_at_least_one_value',
                       'market_data_points', type_='check')
    op.create_check_constraint(
        'ck_market_data_points_has_at_least_one_value',
        'market_data_points',
        'percentile_10 IS NOT NULL OR percentile_25 IS NOT NULL OR '
        'percentile_50 IS NOT NULL OR percentile_75 IS NOT NULL OR '
        'percentile_90 IS NOT NULL OR mean_value IS NOT NULL OR '
        'sample_size IS NOT NULL',
    )
    op.drop_constraint(op.f('uq_market_data_points_natural_key'), 'market_data_points', type_='unique')
    op.create_unique_constraint('uq_market_data_points_natural_key', 'market_data_points', ['country_id', 'taxonomy', 'external_code', 'geographic_scope', 'area_code', 'reference_period', 'experience_band_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added and NOT optional. Survey-derived rows cannot exist in the
    # pre-Phase-11 schema at all: their codes are descriptive strings that
    # overflow the narrower external_code, and suppressed cells carry no
    # figures, which the stricter CHECK forbids. Verified by running the
    # real downgrade with the data present - it failed with
    # `StringDataRightTruncation: value too long for type character
    # varying(16)`.
    #
    # So the downgrade removes exactly the data this migration enabled.
    # That is real, intended data loss, scoped to the survey taxonomy: the
    # BLS rows that predate this migration are untouched, and the survey
    # data is fully reproducible by re-running the ingestion.
    op.execute("DELETE FROM market_data_points WHERE taxonomy = 'SO-DEVTYPE-2025'")
    op.execute("DELETE FROM job_family_occupation_mappings WHERE taxonomy = 'SO-DEVTYPE-2025'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_market_data_points_natural_key', 'market_data_points', type_='unique')
    op.create_unique_constraint(op.f('uq_market_data_points_natural_key'), 'market_data_points', ['country_id', 'taxonomy', 'external_code', 'geographic_scope', 'area_code', 'reference_period'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('ck_market_data_points_has_at_least_one_value',
                       'market_data_points', type_='check')
    op.create_check_constraint(
        'ck_market_data_points_has_at_least_one_value',
        'market_data_points',
        'percentile_10 IS NOT NULL OR percentile_25 IS NOT NULL OR '
        'percentile_50 IS NOT NULL OR percentile_75 IS NOT NULL OR '
        'percentile_90 IS NOT NULL OR mean_value IS NOT NULL',
    )
    op.alter_column('market_data_points', 'external_code',
                    existing_type=sa.String(length=128), type_=sa.String(length=16))
    op.alter_column(
        'job_family_occupation_mappings', 'external_code',
        existing_type=sa.String(length=128), type_=sa.String(length=16),
        comment="Code within `taxonomy`, e.g. '151252' for SOC 15-1252.",
    )
    op.drop_column('market_data_points', 'representativeness_note')
    op.drop_column('market_data_points', 'source_key')
    op.drop_column('market_data_points', 'experience_max_years')
    op.drop_column('market_data_points', 'experience_min_years')
    op.drop_column('market_data_points', 'experience_band_label')
    op.drop_column('market_data_points', 'sample_size')
    # ### end Alembic commands ###
